services:
  - type: web
    name: trading-journal-backend
    env: node
    plan: free
<<<<<<< HEAD
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run prisma:deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_PRODUCTION
        value: false
=======
    buildCommand: npm install && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
>>>>>>> ca97032 (Prepare deployment)
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        value: 30d
